### ISSUE TITLE
Cannot run storybook-react-examples

### ISSUE THREAD

**Issue by togakangaroo** [gvaldambrini/storybook-router#25]
Just cloned the repo and trying to run the examples

```
~/code/storybook-router $ npm install && npm run storybook-react-examples
up to date in 1.811s

> storybook-router@ storybook-react-examples /Users/gmauer/code/storybook-router
> lerna exec --scope storybook-react-router-examples -- npm run storybook

lerna info version 2.9.1
lerna info versioning independent
lerna info scope storybook-react-router-examples

> storybook-react-router-examples@1.0.1 storybook /Users/gmauer/code/storybook-router/examples/react-router
> start-storybook -p 9001 -c .storybook

sh: start-storybook: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! storybook-react-router-examples@1.0.1 storybook: `start-storybook -p 9001 -c .storybook`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the storybook-react-router-examples@1.0.1 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gmauer/.npm/_logs/2018-07-15T20_19_12_344Z-debug.log
lerna ERR! exec Errored while executing 'npm run storybook' in 'storybook-react-router-examples'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run storybook
lerna ERR!     at Promise.all.then.arr (/Users/gmauer/code/storybook-router/node_modules/lerna/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run storybook
    at Promise.all.then.arr (/Users/gmauer/code/storybook-router/node_modules/lerna/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'npm run storybook',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storybook-router@ storybook-react-examples: `lerna exec --scope storybook-react-router-examples -- npm run storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storybook-router@ storybook-react-examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by gvaldambrini** [comment]
Hi @togakangaroo, thank you for the report 😄. This project uses lerna to manage all the dependencies, and the recommended way to install the dependencies and run the examples is already documented:

https://github.com/gvaldambrini/storybook-router/tree/master/packages/react#advanced-usage-and-examples

Feel free to reopen the issue in case I'm missing something.
