### ISSUE TITLE
Problem with using useRouteMatch in storybook

### ISSUE THREAD

**Issue by Bersam** [gvaldambrini/storybook-router#46]
Issue:

### Which version are you using?
"storybook-react-router": "^1.0.8",

### Are you using storybook-router with a react based project or a vue one?
react

### Please describe the problem:
It shows the following error when I use `useRouteMatch` hook:
```js
TypeError: Cannot read property 'match' of undefined
    at useRouteMatch (http://localhost:6007/vendors~main.44791deccf2e14082e5e.bundle.js:138564:78)
.
.
.
    at StoryRouter (http://localhost:6007/vendors~main.44791deccf2e14082e5e.bundle.js:145079:7)

```
Couldn't get unoptimized version because of this issue on storybook, https://github.com/storybookjs/storybook/issues/8062 

### Please explain how to reproduce the issue or (better) provide an example to do it.
```js
const CompanyDetailsPage = () => {
  const { path, params } = useRouteMatch();
  const to = pathToRegexp.compile(path)({
    ...params,
    someparameter: 'someparameter',
  }),

  return (<Link to={to} >Link</Link>)
};
```
should raise mentioned error.

**Comment by thareshjose** [comment]
Any updates on this issue?
